# Generated by Django 3.0.4 on 2020-03-18 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blog_writter', models.CharField(max_length=100)),
                ('blog_type', models.CharField(max_length=100)),
                ('blog_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField()),
            ],
        ),
    ]
