# Generated by Django 3.0.4 on 2020-03-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='no_of_person',
            field=models.CharField(max_length=10),
        ),
    ]
